# Generated by Django 6.0.5 on 2026-06-11 08:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file')),
                ('file_type', models.CharField(choices=[('image', 'Ảnh'), ('file', 'File')], default='file', max_length=10, verbose_name='Loại file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='topics.post', verbose_name='Bài viết')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='topics.topic', verbose_name='Chủ đề')),
            ],
            options={
                'verbose_name': 'Tệp đính kèm',
                'verbose_name_plural': 'Tệp đính kèm',
            },
        ),
    ]
