# Generated by Django 6.0.5 on 2026-06-11 08:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện'),
        ),
    ]
