# Generated by Django 6.0.4 on 2026-05-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=100, verbose_name='Tên chuyên mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Biểu tượng (CSS class hoặc URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forums', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Chuyên mục',
                'verbose_name_plural': 'Chuyên mục',
                'ordering': ['forum_name'],
            },
        ),
    ]
