# Generated by Django 6.0.5 on 2026-06-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
    ]
