# Generated by Django 6.0.5 on 2026-06-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete_post', 'Xóa bài viết'), ('lock_topic', 'Khóa chủ đề'), ('warn_user', 'Cảnh báo người dùng'), ('ban_user', 'Khóa tài khoản'), ('resolve_report', 'Xử lý báo cáo'), ('dismiss_report', 'Bỏ qua báo cáo')], max_length=30, verbose_name='Hành động')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xử lý')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm duyệt')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='interactions.report', verbose_name='Báo cáo liên quan')),
            ],
            options={
                'verbose_name': 'Nhật ký kiểm duyệt',
                'verbose_name_plural': 'Nhật ký kiểm duyệt',
                'ordering': ['-created_at'],
            },
        ),
    ]
